version: '3.9'

services:
  cassandra:
    container_name: casandra
    image: cassandra:latest
    ports:
      - 9042:9042
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9160:9160
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=test_bigdata